Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -43,20 +43,22 @@ jobs:
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
           xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
 
-          # Post-run script to find and upload the Cucumber report
-          TARGET_DEVICE_IDENTIFIER=$(xcrun simctl list devices | grep -oE '([0-9A-F-]{36})' | head -1)
-          FILE_PATH=$(find ~/Library/Developer/CoreSimulator/Devices/$TARGET_DEVICE_IDENTIFIER -name "CucumberTestResultsFor${{ env.TARGET_NAME }}.json" -print0 | xargs -r -0 ls -1 -t | head -1)
-          echo "FILE_PATH=${FILE_PATH}"
-          echo "cucumberReportPath=${FILE_PATH}" >> $GITHUB_ENV
-
-          # Upload Cucumber Report
-          echo "Uploading Cucumber report..."
-          if [ -f "$FILE_PATH" ]; then
-            tar -czvf cucumber-report.tar.gz "$FILE_PATH"
-            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-                 -H "Content-Type: application/octet-stream" \
-                 --data-binary @cucumber-report.tar.gz \
-                 "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }}"
+          # Post-test script to handle report file
+          rm -f $SRCROOT/CucumberReports/ERROR.txt
+          mkdir -p $SRCROOT/CucumberReports
+          if [ "$TARGET_DEVICE_PLATFORM_NAME" == "iphonesimulator" ]; then
+              find ~/Library/Developer/CoreSimulator/Devices/$TARGET_DEVICE_IDENTIFIER -name "CucumberTestResultsFor$TARGETNAME.json" -print0 | xargs -r -0 ls -1 -t | head -1 | xargs -I '{}' mv '{}' $SRCROOT/CucumberReports$TARGETNAME
+          elif [ -x "$(command -v ios-deploy)" ]; then
+              ios-deploy --download=/Documents --bundle_id $PRODUCT_BUNDLE_IDENTIFIER.xctrunner --to "$SRCROOT/CucumberReports"
+              cp "$SRCROOT/CucumberReports/Documents/CucumberTestResultsFor$TARGETNAME.json" "$SRCROOT/CucumberReports/CucumberTestResultsFor$TARGETNAME.json"
+              rm -rf "$SRCROOT/CucumberReports/Documents/"
           else
-            echo "Cucumber report not found!"
+              echo "error: Unable to download CucumberSwift report from actual device, you need the ios-deploy tool installed! Install with 'brew install ios-deploy'" > $SRCROOT/CucumberReports/ERROR.txt
+              exit 1
           fi
+          
+      - name: Upload Cucumber Report
+        uses: actions/upload-artifact@v2
+        with:
+          name: cucumber-reports
+          path: $SRCROOT/CucumberReports/CucumberTestResultsFor$TARGETNAME.json
